// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0F3iV2qHeQWq_SqpnQwL55ERtmkBg5yQ',
    appId: '1:507896320750:web:457ae6b144e4a2e3b8d9ff',
    messagingSenderId: '507896320750',
    projectId: 'distancemate-580b5',
    authDomain: 'distancemate-580b5.firebaseapp.com',
    databaseURL: 'https://distancemate-580b5-default-rtdb.firebaseio.com',
    storageBucket: 'distancemate-580b5.firebasestorage.app',
    measurementId: 'G-3R53BM6MHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPIvOzAAXvliQ55PmF9ofiLiOdeQV4ivw',
    appId: '1:507896320750:android:a5e78279efa9bbc3b8d9ff',
    messagingSenderId: '507896320750',
    projectId: 'distancemate-580b5',
    databaseURL: 'https://distancemate-580b5-default-rtdb.firebaseio.com',
    storageBucket: 'distancemate-580b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM9hL9Py2gjsTW2BN8IgOW4KaBtafGOmE',
    appId: '1:507896320750:ios:75bf24b4075d614cb8d9ff',
    messagingSenderId: '507896320750',
    projectId: 'distancemate-580b5',
    databaseURL: 'https://distancemate-580b5-default-rtdb.firebaseio.com',
    storageBucket: 'distancemate-580b5.firebasestorage.app',
    iosBundleId: 'com.example.distancemate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM9hL9Py2gjsTW2BN8IgOW4KaBtafGOmE',
    appId: '1:507896320750:ios:75bf24b4075d614cb8d9ff',
    messagingSenderId: '507896320750',
    projectId: 'distancemate-580b5',
    databaseURL: 'https://distancemate-580b5-default-rtdb.firebaseio.com',
    storageBucket: 'distancemate-580b5.firebasestorage.app',
    iosBundleId: 'com.example.distancemate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0F3iV2qHeQWq_SqpnQwL55ERtmkBg5yQ',
    appId: '1:507896320750:web:5f3b8632b4ef5c44b8d9ff',
    messagingSenderId: '507896320750',
    projectId: 'distancemate-580b5',
    authDomain: 'distancemate-580b5.firebaseapp.com',
    databaseURL: 'https://distancemate-580b5-default-rtdb.firebaseio.com',
    storageBucket: 'distancemate-580b5.firebasestorage.app',
    measurementId: 'G-9J2HRNCEMW',
  );
}
